name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSKEY }}

      - name: Determine Docker Image Tags
        id: docker_tags
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "tags=bertoja/luminasync-v2:stable-main" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "tags=bertoja/luminasync-v2:latest" >> $GITHUB_ENV
          fi
          
      - name: Build and push Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64/v8 -t ${{ env.tags }} --push .
        env:
          DOCKER_BUILDKIT: 1
